apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: staticweb
  name: staticweb
spec:
  replicas: 2
  selector:
    matchLabels:
      app: staticweb
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: staticweb
    spec:
      containers:
      - image: staticweb
        name: staticweb
        resources: {}
status: {}
