version: "3.9"
services:
  frontend:
    build: ./
    volumes:
      - .:/app
  nginx:
    build: ./nginx
    depends_on:
      - frontend
    ports:
      - "3000:80"
    volumes: 
      - "~/devops/Docker/Buoi_2/tictac/public:/var/www/html"
